[package]
name = "framing"
description = "Fast frames for video and images."
repository = "https://github.com/quadrupleslap/framing"
documentation = "https://docs.rs/framing"
license = "MIT"
version = "0.3.2"
authors = ["Ram <quadrupleslap@gmail.com>"]

[dependencies]
bytes = "0.4"
clamp = "0.1"
rayon = "0.8"
time = "0.1"
